version: '3.4'

services:

  bot:
    env_file: ./bot/.env
    build:
      dockerfile: Dockerfile
      context: ./bot  

  api:
    image: lunchreporterapi:latest
    env_file: .env
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - "1050:80" 

volumes:
  mongodatabase:
    driver: local